/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nurserymanagementsystem;

import javax.swing.JPanel;

/**
 *
 * @author Valeena Afzal
 */
public class EntryOperator extends javax.swing.JFrame {

    /**
     * Creates new form EntryOperator
     */
    public EntryOperator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layers = new javax.swing.JLayeredPane();
        OrderPanel = new javax.swing.JPanel();
        Manage1 = new javax.swing.JPanel();
        CalenderPanel = new javax.swing.JPanel();
        OrderDate = new javax.swing.JLabel();
        jDayChooser2 = new com.toedter.calendar.JDayChooser();
        Formpanel1 = new javax.swing.JPanel();
        ManageInv1 = new javax.swing.JPanel();
        InvType1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Name1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Category1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        Quantity1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        Price1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        CNIC = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        InvHeadingP1 = new javax.swing.JPanel();
        Heading2 = new javax.swing.JLabel();
        MButtonsP2 = new javax.swing.JPanel();
        ButtonsInv2 = new javax.swing.JPanel();
        AddOrder = new javax.swing.JButton();
        EditOrder = new javax.swing.JButton();
        DeleteOrder = new javax.swing.JButton();
        PrintOrder = new javax.swing.JButton();
        ClearOrder = new javax.swing.JButton();
        ViewInv1 = new javax.swing.JPanel();
        HeadingPanel1 = new javax.swing.JPanel();
        Heading3 = new javax.swing.JLabel();
        TablePanel1 = new javax.swing.JPanel();
        PTable1 = new javax.swing.JScrollPane();
        Tables1 = new javax.swing.JTable();
        MailPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton6 = new javax.swing.JButton();
        InventoryPanel = new javax.swing.JPanel();
        Manage = new javax.swing.JPanel();
        MButtonsP = new javax.swing.JPanel();
        ButtonsInv = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        InvHeadingP = new javax.swing.JPanel();
        Heading1 = new javax.swing.JLabel();
        ManageInv = new javax.swing.JPanel();
        InvType = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Name = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Category = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Quantity = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        ViewInv = new javax.swing.JPanel();
        HeadingPanel = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        TablePanel = new javax.swing.JPanel();
        PTable = new javax.swing.JScrollPane();
        Tables = new javax.swing.JTable();
        Menu = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        TLogo = new javax.swing.JLabel();
        Buttons = new javax.swing.JPanel();
        Inventory = new javax.swing.JButton();
        Orders = new javax.swing.JButton();
        Mails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Layers.setLayout(new java.awt.CardLayout());

        OrderPanel.setBackground(new java.awt.Color(255, 255, 255));
        OrderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manage1.setBackground(new java.awt.Color(255, 255, 255));
        Manage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CalenderPanel.setBackground(new java.awt.Color(255, 255, 255));
        CalenderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        OrderDate.setBackground(new java.awt.Color(255, 255, 255));
        OrderDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        OrderDate.setForeground(new java.awt.Color(153, 0, 0));
        OrderDate.setText("Date");
        OrderDate.setPreferredSize(new java.awt.Dimension(130, 50));
        CalenderPanel.add(OrderDate);

        jDayChooser2.setBackground(new java.awt.Color(255, 255, 255));
        CalenderPanel.add(jDayChooser2);

        Formpanel1.setBackground(new java.awt.Color(255, 255, 255));
        Formpanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ManageInv1.setBackground(new java.awt.Color(255, 255, 255));
        ManageInv1.setLayout(new java.awt.GridLayout(3, 4, 15, 30));

        InvType1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        InvType1.setForeground(new java.awt.Color(153, 0, 0));
        InvType1.setText("Select Type");
        ManageInv1.add(InvType1);

        jComboBox3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruit Trees", "Trees", "Shrubs", "Herbs", "Climbers", "Creepers", "None" }));
        ManageInv1.add(jComboBox3);

        Name1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Name1.setForeground(new java.awt.Color(153, 0, 0));
        Name1.setText("Name");
        ManageInv1.add(Name1);

        jTextField5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField5);

        Category1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Category1.setForeground(new java.awt.Color(153, 0, 0));
        Category1.setText("Category");
        ManageInv1.add(Category1);

        jComboBox4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plants", "Seeds", "Tools" }));
        ManageInv1.add(jComboBox4);

        Quantity1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Quantity1.setForeground(new java.awt.Color(153, 0, 0));
        Quantity1.setText("Quantity");
        ManageInv1.add(Quantity1);

        jTextField6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField6);

        Price1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Price1.setForeground(new java.awt.Color(153, 0, 0));
        Price1.setText("Price");
        ManageInv1.add(Price1);

        jTextField7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField7);

        CNIC.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CNIC.setForeground(new java.awt.Color(153, 0, 0));
        CNIC.setText("CNIC");
        ManageInv1.add(CNIC);

        jTextField8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField8);

        Formpanel1.add(ManageInv1);

        InvHeadingP1.setBackground(new java.awt.Color(255, 255, 255));

        Heading2.setBackground(new java.awt.Color(153, 0, 0));
        Heading2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading2.setForeground(new java.awt.Color(153, 0, 0));
        Heading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading2.setText("Manage Orders");
        InvHeadingP1.add(Heading2);

        MButtonsP2.setBackground(new java.awt.Color(255, 255, 255));
        MButtonsP2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        ButtonsInv2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonsInv2.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        AddOrder.setBackground(new java.awt.Color(153, 0, 0));
        AddOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AddOrder.setForeground(new java.awt.Color(255, 255, 255));
        AddOrder.setText("Add");
        ButtonsInv2.add(AddOrder);

        EditOrder.setBackground(new java.awt.Color(153, 0, 0));
        EditOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EditOrder.setForeground(new java.awt.Color(255, 255, 255));
        EditOrder.setText("Edit");
        EditOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOrderActionPerformed(evt);
            }
        });
        ButtonsInv2.add(EditOrder);

        DeleteOrder.setBackground(new java.awt.Color(153, 0, 0));
        DeleteOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DeleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        DeleteOrder.setText("Delete");
        DeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteOrderActionPerformed(evt);
            }
        });
        ButtonsInv2.add(DeleteOrder);

        PrintOrder.setBackground(new java.awt.Color(153, 0, 0));
        PrintOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PrintOrder.setForeground(new java.awt.Color(255, 255, 255));
        PrintOrder.setText("Print");
        PrintOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintOrderActionPerformed(evt);
            }
        });
        ButtonsInv2.add(PrintOrder);

        ClearOrder.setBackground(new java.awt.Color(153, 0, 0));
        ClearOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ClearOrder.setForeground(new java.awt.Color(255, 255, 255));
        ClearOrder.setText("Clear");
        ButtonsInv2.add(ClearOrder);

        MButtonsP2.add(ButtonsInv2);

        javax.swing.GroupLayout Manage1Layout = new javax.swing.GroupLayout(Manage1);
        Manage1.setLayout(Manage1Layout);
        Manage1Layout.setHorizontalGroup(
            Manage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvHeadingP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MButtonsP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
            .addGroup(Manage1Layout.createSequentialGroup()
                .addComponent(Formpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(CalenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Manage1Layout.setVerticalGroup(
            Manage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Manage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvHeadingP1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Manage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Formpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(MButtonsP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        OrderPanel.add(Manage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 410));

        ViewInv1.setBackground(new java.awt.Color(255, 255, 255));
        ViewInv1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HeadingPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Heading3.setBackground(new java.awt.Color(153, 0, 0));
        Heading3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading3.setForeground(new java.awt.Color(153, 0, 0));
        Heading3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading3.setText("Inventory List");

        javax.swing.GroupLayout HeadingPanel1Layout = new javax.swing.GroupLayout(HeadingPanel1);
        HeadingPanel1.setLayout(HeadingPanel1Layout);
        HeadingPanel1Layout.setHorizontalGroup(
            HeadingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading3, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        HeadingPanel1Layout.setVerticalGroup(
            HeadingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        TablePanel1.setBackground(new java.awt.Color(255, 255, 255));
        TablePanel1.setForeground(new java.awt.Color(153, 0, 0));

        PTable1.setBackground(new java.awt.Color(153, 0, 0));
        PTable1.setBorder(null);
        PTable1.setForeground(new java.awt.Color(255, 255, 255));
        PTable1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Tables1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Tables1.setForeground(new java.awt.Color(153, 0, 0));
        Tables1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Name", "Date", "CNIC", "Quantity", "Price", "Category"
            }
        ));
        Tables1.setGridColor(new java.awt.Color(153, 0, 0));
        Tables1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tables1.setSelectionForeground(new java.awt.Color(255, 153, 204));
        PTable1.setViewportView(Tables1);

        javax.swing.GroupLayout TablePanel1Layout = new javax.swing.GroupLayout(TablePanel1);
        TablePanel1.setLayout(TablePanel1Layout);
        TablePanel1Layout.setHorizontalGroup(
            TablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        TablePanel1Layout.setVerticalGroup(
            TablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout ViewInv1Layout = new javax.swing.GroupLayout(ViewInv1);
        ViewInv1.setLayout(ViewInv1Layout);
        ViewInv1Layout.setHorizontalGroup(
            ViewInv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadingPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TablePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ViewInv1Layout.setVerticalGroup(
            ViewInv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewInv1Layout.createSequentialGroup()
                .addComponent(HeadingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TablePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OrderPanel.add(ViewInv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 407, 1130, 300));

        Layers.add(OrderPanel, "card3");

        MailPanel.setBackground(new java.awt.Color(255, 255, 255));
        MailPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(5.0F);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(5.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 550));

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Subject");

        jTextField9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(153, 0, 0));

        jLabel4.setBackground(new java.awt.Color(153, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("From");

        jTextField11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(153, 0, 0));
        jTextField11.setText("valeenaafzal@gmail.com");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Content");

        jTextField12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(153, 0, 0));

        jLabel6.setBackground(new java.awt.Color(153, 0, 0));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select Attachment");

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Send To");

        jTextField10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(153, 0, 0));

        jLabel7.setBackground(new java.awt.Color(153, 0, 0));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Send To");

        jButton6.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 0));
        jButton6.setText("Send");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(165, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        MailPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1130, -1));

        Layers.add(MailPanel, "card4");

        InventoryPanel.setBackground(new java.awt.Color(51, 51, 51));
        InventoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manage.setBackground(new java.awt.Color(255, 255, 255));
        Manage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Manage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MButtonsP.setBackground(new java.awt.Color(255, 255, 255));

        ButtonsInv.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");

        javax.swing.GroupLayout ButtonsInvLayout = new javax.swing.GroupLayout(ButtonsInv);
        ButtonsInv.setLayout(ButtonsInvLayout);
        ButtonsInvLayout.setHorizontalGroup(
            ButtonsInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsInvLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton3)
                .addGap(0, 0, 0)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ButtonsInvLayout.setVerticalGroup(
            ButtonsInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
            .addComponent(jButton2)
            .addComponent(jButton3)
            .addComponent(jButton4)
        );

        javax.swing.GroupLayout MButtonsPLayout = new javax.swing.GroupLayout(MButtonsP);
        MButtonsP.setLayout(MButtonsPLayout);
        MButtonsPLayout.setHorizontalGroup(
            MButtonsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MButtonsPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ButtonsInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        MButtonsPLayout.setVerticalGroup(
            MButtonsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MButtonsPLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ButtonsInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Manage.add(MButtonsP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 371, -1, -1));

        InvHeadingP.setBackground(new java.awt.Color(255, 255, 255));

        Heading1.setBackground(new java.awt.Color(153, 0, 0));
        Heading1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading1.setForeground(new java.awt.Color(153, 0, 0));
        Heading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading1.setText("Manage Inventory");

        javax.swing.GroupLayout InvHeadingPLayout = new javax.swing.GroupLayout(InvHeadingP);
        InvHeadingP.setLayout(InvHeadingPLayout);
        InvHeadingPLayout.setHorizontalGroup(
            InvHeadingPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvHeadingPLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(Heading1)
                .addContainerGap(826, Short.MAX_VALUE))
        );
        InvHeadingPLayout.setVerticalGroup(
            InvHeadingPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvHeadingPLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Heading1))
        );

        Manage.add(InvHeadingP, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, -1, -1));

        ManageInv.setBackground(new java.awt.Color(255, 255, 255));
        ManageInv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InvType.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        InvType.setForeground(new java.awt.Color(153, 0, 0));
        InvType.setText("Select Type");
        ManageInv.add(InvType, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 29));

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruit Trees", "Trees", "Shrubs", "Herbs", "Climbers", "Creepers", "None" }));
        ManageInv.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        Name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 0, 0));
        Name.setText("Name");
        ManageInv.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, 120, 29));

        jTextField3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 59, 120, -1));

        Category.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Category.setForeground(new java.awt.Color(153, 0, 0));
        Category.setText("Category");
        ManageInv.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 120, 29));

        jComboBox2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plants", "Seeds", "Tools" }));
        ManageInv.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 118, 120, -1));

        Quantity.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Quantity.setForeground(new java.awt.Color(153, 0, 0));
        Quantity.setText("Quantity");
        ManageInv.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 120, 29));

        jTextField2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 177, 120, -1));

        Price.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(153, 0, 0));
        Price.setText("Price");
        ManageInv.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 120, 29));

        jTextField4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 236, 120, -1));

        Manage.add(ManageInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 88, 510, -1));

        InventoryPanel.add(Manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 420));

        ViewInv.setBackground(new java.awt.Color(255, 255, 255));
        ViewInv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ViewInv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeadingPanel.setBackground(new java.awt.Color(255, 255, 255));

        Heading.setBackground(new java.awt.Color(153, 0, 0));
        Heading.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading.setForeground(new java.awt.Color(153, 0, 0));
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Inventory List");

        javax.swing.GroupLayout HeadingPanelLayout = new javax.swing.GroupLayout(HeadingPanel);
        HeadingPanel.setLayout(HeadingPanelLayout);
        HeadingPanelLayout.setHorizontalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        HeadingPanelLayout.setVerticalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ViewInv.add(HeadingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 7, 1240, 50));

        TablePanel.setBackground(new java.awt.Color(255, 255, 255));
        TablePanel.setForeground(new java.awt.Color(153, 0, 0));

        PTable.setBackground(new java.awt.Color(153, 0, 0));
        PTable.setBorder(null);
        PTable.setForeground(new java.awt.Color(255, 255, 255));
        PTable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Tables.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Tables.setForeground(new java.awt.Color(153, 0, 0));
        Tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Name", "Quantity", "Price", "Category"
            }
        ));
        Tables.setGridColor(new java.awt.Color(153, 0, 0));
        Tables.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tables.setSelectionForeground(new java.awt.Color(255, 153, 204));
        PTable.setViewportView(Tables);

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addComponent(PTable, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ViewInv.add(TablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1240, 320));

        InventoryPanel.add(ViewInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 420, 1250, 380));

        Layers.add(InventoryPanel, "card2");

        getContentPane().add(Layers, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1130, 710));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Logo.setBackground(new java.awt.Color(255, 255, 255));

        Buttons.setBackground(new java.awt.Color(255, 255, 255));
        Buttons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventory.setBackground(new java.awt.Color(153, 0, 0));
        Inventory.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setText("Update Inventory");
        Inventory.setPreferredSize(new java.awt.Dimension(120, 50));
        Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryActionPerformed(evt);
            }
        });
        Buttons.add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 187, -1));

        Orders.setBackground(new java.awt.Color(153, 0, 0));
        Orders.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Orders.setForeground(new java.awt.Color(255, 255, 255));
        Orders.setText("Add Order");
        Orders.setPreferredSize(new java.awt.Dimension(120, 50));
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });
        Buttons.add(Orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 187, -1));

        Mails.setBackground(new java.awt.Color(153, 0, 0));
        Mails.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Mails.setForeground(new java.awt.Color(255, 255, 255));
        Mails.setText("Email");
        Mails.setPreferredSize(new java.awt.Dimension(120, 50));
        Mails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailsActionPerformed(evt);
            }
        });
        Buttons.add(Mails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 187, -1));

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TLogo)
                .addGap(197, 197, 197))
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(TLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 240, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EditOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditOrderActionPerformed

    private void DeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteOrderActionPerformed

    private void PrintOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintOrderActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void MailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailsActionPerformed
        SwitchPanels(MailPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_MailsActionPerformed

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        SwitchPanels(OrderPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersActionPerformed

    private void InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryActionPerformed
        SwitchPanels(InventoryPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryActionPerformed

    public void SwitchPanels(JPanel panel)
    {
        Layers.removeAll();
        Layers.add(panel);
        Layers.repaint();
        Layers.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryOperator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrder;
    private javax.swing.JPanel Buttons;
    private javax.swing.JPanel ButtonsInv;
    private javax.swing.JPanel ButtonsInv2;
    private javax.swing.JLabel CNIC;
    private javax.swing.JPanel CalenderPanel;
    private javax.swing.JLabel Category;
    private javax.swing.JLabel Category1;
    private javax.swing.JButton ClearOrder;
    private javax.swing.JButton DeleteOrder;
    private javax.swing.JButton EditOrder;
    private javax.swing.JPanel Formpanel1;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading1;
    private javax.swing.JLabel Heading2;
    private javax.swing.JLabel Heading3;
    private javax.swing.JPanel HeadingPanel;
    private javax.swing.JPanel HeadingPanel1;
    private javax.swing.JPanel InvHeadingP;
    private javax.swing.JPanel InvHeadingP1;
    private javax.swing.JLabel InvType;
    private javax.swing.JLabel InvType1;
    private javax.swing.JButton Inventory;
    private javax.swing.JPanel InventoryPanel;
    private javax.swing.JLayeredPane Layers;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel MButtonsP;
    private javax.swing.JPanel MButtonsP2;
    private javax.swing.JPanel MailPanel;
    private javax.swing.JButton Mails;
    private javax.swing.JPanel Manage;
    private javax.swing.JPanel Manage1;
    private javax.swing.JPanel ManageInv;
    private javax.swing.JPanel ManageInv1;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel OrderDate;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JButton Orders;
    private javax.swing.JScrollPane PTable;
    private javax.swing.JScrollPane PTable1;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Price1;
    private javax.swing.JButton PrintOrder;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel Quantity1;
    private javax.swing.JLabel TLogo;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JPanel TablePanel1;
    private javax.swing.JTable Tables;
    private javax.swing.JTable Tables1;
    private javax.swing.JPanel ViewInv;
    private javax.swing.JPanel ViewInv1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDayChooser jDayChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
